baseURL = 'https://www.roydejesus.com'
languageCode = 'en-us'
title = 'Roy De Jesus'
theme = 'risotto'
paginate = 3
DefaultContentLanguage = "en"
enableInlineShortcodes = true

sectionPagesMenu = "main"

[params]

[params.theme]
palette = "gruvbox-dark"
mode = "dark-mode"

# Sidebar: about/bio
[params.about]
title = "Roy De Jesus"
description = "DevOps Engineer | Build/Release Engineer | Software Developer"
logo = "images/rice.svg"

[[params.socialLinks]]
icon = "fab fa-linkedin fa-2x"
title = "Linkedin"
url = "https://www.linkedin.com/in/roy-de-jesus-146166240"

[[params.socialLinks]]
icon = "fab fa-github fa-2x"
title = "GitHub"
url = "https://github.com/roydejesus1031?tab=repositories"

[[params.socialLinks]]
icon = "fas fa-envelope fa-2x"
title = "Email"
url = "mailto:roydejesus1031@gmail.com"

[menu]

  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 10

[taxonomies]
category = "categories"
tag = "tags"
series = "series"
