baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'Roy De Jesus | Infrastructure Engineer'
theme = 'risotto'

sectionPagesMenu = "main"

[params]

[params.theme]
palette = "gruvbox-dark"
mode = "dark-mode"

# Sidebar: about/bio
[params.about]
title = "Roy De Jesus"
description = "DevOps Engineer  Build/Release Engineer  Software Developer"
logo = "images/rice.svg"

[[params.socialLinks]]
icon = "fab fa-linkedin"
title = "Linkedin"
url = "https://www.linkedin.com/in/roy-de-jesus-146166240"

[[params.socialLinks]]
icon = "fab fa-github"
title = "GitHub"
url = "https://github.com/roydejesus1031?tab=repositories"

[[params.socialLinks]]
icon = "fas fa-envelope"
title = "Email"
url = "mailto:roydejesus1031@gmail.com"

[menu]

  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 10

[taxonomies]
category = "categories"
tag = "tags"
series = "series"
