name: Build and Deploy to Cloud Storage

on:
  push:
    branches:
      - "main"
    paths:
      - site/**

env:
  SITE_SOURCE: ./site
  HUGO_CMD: ' --minify'
  STORAGE_BUCKET: 'roy-dejesus-website'

jobs:
  deploy:
    permissions:
      contents: 'read'
      id-token: 'write'
      
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Build Hugo site
        uses: klakegg/actions-hugo@1.0.0
        with:
          source: ${{ env.SITE_SOURCE }}
          command: ${{ env.HUGO_CMD }}
          
      - name: Auth to Google Cloud Storage
        uses: 'google-github-actions/auth@v0'
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_ID_PROV }}
          service_account: ${{ secrets.GCP_SVC_ACC }}

      - name: Upload to Google Cloud Storage
        uses: 'google-github-actions/upload-cloud-storage@v0'
        with:
          path: '${{ env.SITE_SOURCE }}/public'
          destination: ${{ env.STORAGE_BUCKET }}
          parent: false
