name: Build and Deploy to Cloud Storage

on:
  push:
    branches:
      - "main"

env:
  SITE_SOURCE: ./site
  HUGO_CMD: ' --minify'
  STORAGE_BUCKET: 'roy-dejesus-website-test'
  GCP_WORKLOAD_ID_PROV: 'projects/228867922771/locations/global/workloadIdentityPools/github-actions/providers/github-provider'
  GCP_SVC_ACC: 'personal-website-deploy@website-test-353100.iam.gserviceaccount.com'

jobs:
  deploy:
    # Add 'id-token' with the intended permissions for workload identity federation
    permissions:
      contents: 'read'
      id-token: 'write'
      
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Build Hugo site
        uses: klakegg/actions-hugo@1.0.0
        with:
          source: ${{ env.SITE_SOURCE }}
          command: ${{ env.HUGO_CMD }}
          
      - name: Auth to Google Cloud Storage
        uses: 'google-github-actions/auth@v0'
        with:
          workload_identity_provider: ${{ env.GCP_WORKLOAD_ID_PROV }}
          service_account: ${{ env.GCP_SVC_ACC }}

      - name: Upload to Google Cloud Storage
        uses: 'google-github-actions/upload-cloud-storage@v0'
        with:
          path: '${{ env.SITE_SOURCE }}/public'
          destination: ${{ env.STORAGE_BUCKET }}
          parent: false
