name: Deploy Infrastructure

on:
  push:
    branches:
      - "main"
    paths:
      - terraform/**
      - .github/workflows/deploy-infra.yml

env:
  TF_DIR: ./terraform

jobs:
  deploy:
    permissions:
      contents: 'read'
      id-token: 'write'

    runs-on: ubuntu-latest
    environment: infrastructure
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Auth to Google Cloud Storage
        uses: 'google-github-actions/auth@v0'
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_ID_PROV }}
          service_account: ${{ secrets.GCP_SVC_ACC }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Check TF format
        run: terraform -chdir=$TF_DIR fmt -check

      - name: Init TF
        run: terraform -chdir=$TF_DIR init

      - name: Validate TF
        run: terraform -chdir=$TF_DIR validate -no-color

      - name: Plan TF
        run: terraform -chdir=$TF_DIR plan -out planfile

      - name: Apply TF plan
        run: terraform -chdir=$TF_DIR apply "planfile"
